name: Build currently maintaining source

on:
  workflow_dispatch:

jobs:
  format-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Format new release
        uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'current'
          name: "Currently maintained source code packages"
          body: |
            For
            - Windows Server 2008 R2
            - Windows 7
            - Windows Server 2012
            - Windows Server 2012 R2
            - Windows 8.1
          prerelease: true

  build:
    runs-on: ubuntu-latest
    needs: format-release
    permissions:
      contents: write
    strategy:
      matrix:
        buildtarget: ['26', '27']
      fail-fast: false
    steps:
      - name: Show workflow information
        run: |
          _NAME="go-win7-win6-1.${{ matrix.buildtarget }}"
          echo "SOURCE PACKET GOVER: 1.${{ matrix.buildtarget }}"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Download source
        uses: actions/checkout@v7
        with:
          repository: 'golang/go'
          ref: 'release-branch.go1.${{ matrix.buildtarget }}'
          path: 'go'

      - name: Download patch
        uses: actions/checkout@v7
        with:
          path: 'patch'

      - name: Apply patch
        run: |
          cd ./go
          patch --verbose -p 1 < ../patch/go-1-${{ matrix.buildtarget }}.diff
          cd ..

      - name: Copy License
        run: |
          cp -f ./patch/LICENSE ./go/

      - name: Upload package to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ASSET_NAME }}
          path: |
            ./go/*

      - name: create ZIP archive
        shell: bash
        run: |
          cd ./go/
          zip -9vr ./${{ env.ASSET_NAME }}.zip . -x "./.*" "./.*/*" "./**/.*" "./**/.*/*" "./**/*_test.go" "./**/testdata"
          cd ../

      - name: Compute hashes for file
        run: |
          cd ./go/
          FILE=./${{ env.ASSET_NAME }}.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done
          cd ../

      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./go/${{ env.ASSET_NAME }}.zip*
          tag: current
          file_glob: true
