name: Builder test Go 1.22

on:
  workflow_dispatch:
  #schedule:
    #- cron: '5 0 * * 4,6'
  push:
    branches:
      - build
      - "release-branch.go1.22"
    paths:
      - ".github/workflows/test-go1_22_src.yml"
      - "**/*.go"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - build
      - "release-branch.go1.22"
    paths:
      - ".github/workflows/test-go1_22_src.yml"
      - "**/*.go"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download source
        uses: actions/checkout@v4
        with:
          repository: 'golang/go'
          ref: 'release-branch.go1.22'

      # Patches for Go 1.22.x before more minor changes introduces.
      - name: Apply patch
        run: |
          curl https://github.com/XTLS/go-win7/commit/e4701f06a6358bda901e72cbff44f414d902e988.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/41373f90356fd86e9cbe78c7a71c76066a6730c1.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/481cebf65c4052379cf3cda5db5588c48f2446f6.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/21d5caecf644a12d938c45f18e2b55f04b47f0b0.diff | patch --verbose -p 1

      - name: Set-up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'src\go.mod'
          check-latest: true

      - name: Test patched Go
        run: |
          cd .\src
          .\all.bat
          cd ..\
