name: Builder test Go 1.24

on:
  workflow_dispatch:
  schedule:
    - cron: '25 0 1-20 * 2,4,6'
    - cron: '25 0 21-31 * 6'
  push:
    branches:
      - build
      - release-branch.go1.24
    paths:
      - ".github/workflows/test-go1_24_src.yml"
      - "**/*.go"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - build
      - release-branch.go1.24
    paths:
      - ".github/workflows/test-go1_24_src.yml"
      - "**/*.go"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set-up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Download source
        uses: actions/checkout@v4
        with:
          repository: 'golang/go'
          ref: 'release-branch.go1.24'

      # Patches for Go 1.24.x before more minor changes introduces.
      - name: Apply patch
        run: |
          curl https://github.com/XTLS/go-win7/commit/f429f15f6305e4432afd7309b317e903bd76a5c0.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/41f545de980e9285b68ece40d4b4e63feef9c5a1.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/b6c99a977f732ee5553ddc75ae0fe3b47927fc1c.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/36d7775e030192d3bf2dc111d1f6cfa89eae5f0c.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/a3e4d4735a5d89f60b907308b556c5a53614914d.diff | patch --verbose -p 1

      - name: Test patched Go
        shell: bash
        run: |
          cd ./src
          . ./all.bash
          cd ..
