name: Builder test Go 1.24

on:
  workflow_dispatch:
  schedule:
    # Update on every day
    - cron: '15 0 * * 2,4,6'
  push:
    branches:
      - build
      - release-branch.go1.23
    paths:
      - ".github/workflows/test-go1_23.yml"
      - "**/*.go"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - build
      - release-branch.go1.23
    paths:
      - ".github/workflows/test-go1_23.yml"
      - "**/*.go"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set-up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Download source
        uses: actions/checkout@v4
        with:
          repository: 'golang/go'
          ref: 'release-branch.go1.23'

      # Patches for Go 1.23.x before more minor changes introduces.
      - name: Apply patch
        run: |
          curl https://github.com/XTLS/go-win7/commit/429f9a72007759a757c8e96a2763306c076dbb8f.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/ca03d8ed77dab8b91b69a9d44e6e56844fbcd5d8.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/719ab22f14443a88dd274f7a41afb86dd41628b1.diff | patch --verbose -p 1
          curl https://github.com/XTLS/go-win7/commit/ac17c301268dd7835236e61c9bfefdf2b8e633d5.diff | patch --verbose -p 1

      - name: Test patched Go
        shell: bash
        run: |
          cd ./src
          . ./all.bash
          cd ..
